name: HeadshotAirBattle
options:
  bundleIdPrefix: com.headshotairbattle
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    exactVersion: 11.6.0

targets:
  HeadshotAirBattle:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - HeadshotAirBattle
    settings:
      base:
        INFOPLIST_FILE: HeadshotAirBattle/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.headshotairbattle.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseDatabase

  HeadshotAirBattleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - HeadshotAirBattleTests
    dependencies:
      - target: HeadshotAirBattle
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/HeadshotAirBattle.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/HeadshotAirBattle"
